/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/input.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    SelectInput: typeof import('./src/components/SelectInput.vue')['default']
  }
}
